// <auto-generated />
namespace dev.scan_back.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ProductFile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductFile));
        
        string IMigrationMetadata.Id
        {
            get { return "201811202154495_ProductFile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
